version: "3" # Version of docker-compose

services:
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql-server-container
    hostname: mssql-server
    restart: "no"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "mssql"
      MSSQL_PID: "Express"
    ports:
      - "1443:1443"
    volumes:
      - ./docker_volumes/mssql_data/:/var/opt/mssql/
